# Generated by Django 2.0.6 on 2018-06-27 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkuUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=225, verbose_name='Sku')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sku_users',
            },
        ),
        migrations.CreateModel(
            name='StockLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fun', models.CharField(max_length=225, verbose_name='Sku')),
                ('description', models.TextField(verbose_name='Description')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stock_logs',
            },
        ),
        migrations.CreateModel(
            name='Thresholds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=225, verbose_name='Sku')),
                ('warehouse', models.CharField(max_length=225, verbose_name='Warehouse')),
                ('threshold', models.IntegerField(default=0, verbose_name='Threshold')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
            ],
            options={
                'db_table': 'stock_thresholds',
            },
        ),
        migrations.CreateModel(
            name='WarehouseStocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=225, verbose_name='Sku')),
                ('warehouse', models.CharField(max_length=225, verbose_name='Warehouse')),
                ('qty', models.IntegerField(default=0, verbose_name='Qty')),
                ('is_new', models.IntegerField(default=1, verbose_name='Is New')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
            ],
            options={
                'db_table': 'warehouse_stocks',
            },
        ),
    ]
