# Generated by Django 2.0.6 on 2018-07-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('max_stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=225, verbose_name='Email')),
                ('code', models.CharField(max_length=225, verbose_name='Code')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
            ],
            options={
                'db_table': 'amazon_code',
            },
        ),
    ]
