# Generated by Django 2.0.6 on 2018-07-12 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('max_stock', '0002_amazoncode'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=225, verbose_name='Order Id')),
                ('sku', models.CharField(max_length=50, verbose_name='SKU')),
                ('order_status', models.CharField(max_length=50, verbose_name='Status')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('is_email', models.IntegerField(default=0, verbose_name='Is Email')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
            ],
            options={
                'db_table': 'order_items',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, verbose_name='SKU')),
                ('time_str', models.CharField(max_length=50, verbose_name='Time Str')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
            ],
            options={
                'db_table': 'schedule',
            },
        ),
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, verbose_name='SKU')),
                ('content', models.TextField(verbose_name='Content')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
            ],
            options={
                'db_table': 'templates',
            },
        ),
        migrations.AddField(
            model_name='schedule',
            name='templates',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='max_stock.Templates'),
        ),
    ]
