# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 01:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsinReviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.CharField(max_length=50, verbose_name='AsinId')),
                ('positive_keywords', models.CharField(default='', max_length=255, verbose_name='Positive Keywords')),
                ('negative_keywords', models.CharField(default='', max_length=255, verbose_name='Negative Keywords')),
                ('avg_score', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Avg Score')),
                ('total_review', models.IntegerField(default=0, verbose_name='Total Reviews')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Create Date')),
            ],
            options={
                'db_table': 'asin_reviews',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='User')),
                ('asin', models.CharField(max_length=50, verbose_name='AsinId')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('variation', models.CharField(max_length=255, verbose_name='Variation')),
                ('content', models.TextField(default='', verbose_name='Content')),
                ('review_link', models.CharField(max_length=500, verbose_name='Review Link')),
                ('score', models.IntegerField(default=0, verbose_name='Score')),
                ('is_vp', models.IntegerField(default=0, verbose_name='VP')),
                ('review_date', models.DateField(verbose_name='Date')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Create Date')),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
        migrations.CreateModel(
            name='UserAsins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.CharField(max_length=50, verbose_name='AsinId')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Field')),
                ('alias', models.CharField(default='', max_length=255, verbose_name='Alias')),
                ('is_email', models.BooleanField(default=1, verbose_name='是否邮件通知')),
                ('is_use', models.BooleanField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_asins',
            },
        ),
    ]
