# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxlead_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='variation',
            field=models.CharField(default='', max_length=255, verbose_name='Variation'),
        ),
    ]
