# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxlead_site', '0002_auto_20171128_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='variation',
            field=models.CharField(default=None, max_length=255, verbose_name='Variation'),
        ),
    ]
