# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxlead_site', '0003_auto_20171128_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='variation',
            field=models.CharField(max_length=255, null=True, verbose_name='Variation'),
        ),
    ]
