# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxlead_site', '0004_auto_20171128_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asinreviews',
            name='negative_keywords',
            field=models.CharField(max_length=255, null=True, verbose_name='Negative Keywords'),
        ),
        migrations.AlterField(
            model_name='asinreviews',
            name='positive_keywords',
            field=models.CharField(max_length=255, null=True, verbose_name='Positive Keywords'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='is_vp',
            field=models.IntegerField(default=0, null=True, verbose_name='VP'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='review_link',
            field=models.CharField(max_length=500, null=True, verbose_name='Review Link'),
        ),
    ]
