# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxlead_site', '0008_auto_20171130_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='image_names',
            field=models.CharField(max_length=255, null=True, verbose_name='Images'),
        ),
    ]
