# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxlead_site', '0010_auto_20171204_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='image_urls',
            field=models.TextField(null=True, verbose_name='Image Urls'),
        ),
    ]
