# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxlead_site', '0011_reviews_image_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='image_names',
            field=models.TextField(null=True, verbose_name='Images'),
        ),
    ]
